import type { Product } from "./types"

export const products: Product[] = [
  // Original fragrances
  {
    id: "louis-vuitton",
    name: "Louis Vuitton Inspired",
    description: "A luxurious fragrance inspired by Louis Vuitton with notes of leather, wood, and spice.",
    price: 25.75,
    category: "Premium Cologne",
    imageUrl: "/images/louis-vuitton.jpeg",
    images: [
      "/images/louis-vuitton.jpeg",
      "/images/louis-vuitton.jpeg",
      "/images/louis-vuitton.jpeg",
      "/images/louis-vuitton.jpeg",
    ],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "jimmy-choo",
    name: "Jimmy Choo Inspired",
    description: "An elegant fragrance inspired by Jimmy Choo with floral and fruity notes.",
    price: 25.75,
    category: "Premium Cologne",
    imageUrl: "/images/jimmy-choo.jpeg",
    images: ["/images/jimmy-choo.jpeg", "/images/jimmy-choo.jpeg", "/images/jimmy-choo.jpeg"],
    gender: "female",
    type: "fragrance",
  },
  {
    id: "prada",
    name: "Prada Inspired",
    description: "A sophisticated fragrance inspired by Prada with amber and musk notes.",
    price: 25.75,
    category: "Premium Cologne",
    imageUrl: "/images/prada.jpeg",
    images: ["/images/prada.jpeg", "/images/prada.jpeg", "/images/prada.jpeg"],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "aqua-de-gio",
    name: "Aqua De Gio Inspired",
    description: "A fresh, aquatic fragrance inspired by Acqua Di Gio with citrus and marine notes.",
    price: 25.75,
    category: "Premium Cologne",
    imageUrl: "/images/aqua-de-gio.jpeg",
    images: ["/images/aqua-de-gio.jpeg", "/images/aqua-de-gio.jpeg", "/images/aqua-de-gio.jpeg"],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "sugar-girl",
    name: "Sugar Girl",
    description: "A sweet and playful fragrance with vanilla and caramel notes.",
    price: 25.75,
    category: "Premium Cologne",
    imageUrl: "/images/sugar-girl.jpeg",
    images: ["/images/sugar-girl.jpeg", "/images/sugar-girl.jpeg", "/images/sugar-girl.jpeg"],
    gender: "female",
    type: "fragrance",
  },
  {
    id: "gucci-guilty",
    name: "Gucci Guilty Inspired",
    description: "A bold fragrance inspired by Gucci Guilty with spicy and floral notes.",
    price: 25.75,
    category: "Premium Cologne",
    imageUrl: "/images/gucci-guilty.jpeg",
    images: ["/images/gucci-guilty.jpeg", "/images/gucci-guilty.jpeg", "/images/gucci-guilty.jpeg"],
    gender: "male",
    type: "fragrance",
  },

  // Additional men's fragrances
  {
    id: "ysl",
    name: "YSL Inspired",
    description: "A sophisticated and elegant fragrance inspired by YSL with woody and aromatic notes.",
    price: 25.75,
    category: "Men's Fragrance",
    imageUrl: "/images/ysl.jpeg",
    images: ["/images/ysl.jpeg", "/images/ysl.jpeg", "/images/ysl.jpeg"],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "creed-himalaya",
    name: "Creed Himalaya Inspired",
    description:
      "A crisp and refreshing fragrance inspired by Creed Himalaya with notes of citrus, sandalwood, and musk.",
    price: 25.75,
    category: "Men's Fragrance",
    imageUrl: "/images/creed-himalaya.jpeg",
    images: ["/images/creed-himalaya.jpeg", "/images/creed-himalaya.jpeg", "/images/creed-himalaya.jpeg"],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "tommy-bahamas",
    name: "Tommy Bahamas Inspired",
    description:
      "A tropical and refreshing fragrance inspired by Tommy Bahamas with notes of citrus, sea breeze, and exotic woods.",
    price: 25.75,
    category: "Men's Fragrance",
    imageUrl: "/images/tommy-bahamas.jpeg",
    images: ["/images/tommy-bahamas.jpeg", "/images/tommy-bahamas.jpeg", "/images/tommy-bahamas.jpeg"],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "creed-aventus",
    name: "Creed Aventus Inspired",
    description:
      "A luxurious and powerful fragrance inspired by Creed Aventus with notes of pineapple, blackcurrant, birch, and ambergris.",
    price: 25.75,
    category: "Men's Fragrance",
    imageUrl: "/images/creed-aventus.jpeg",
    images: ["/images/creed-aventus.jpeg", "/images/creed-aventus.jpeg", "/images/creed-aventus.jpeg"],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "givenchy-gentleman",
    name: "Givenchy Gentleman Inspired",
    description:
      "A refined and elegant fragrance inspired by Givenchy Gentleman with notes of pear, cardamom, iris, and patchouli.",
    price: 25.75,
    category: "Men's Fragrance",
    imageUrl: "/images/givenchy-gentleman.jpeg",
    images: ["/images/givenchy-gentleman.jpeg", "/images/givenchy-gentleman.jpeg", "/images/givenchy-gentleman.jpeg"],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "armani",
    name: "Armani Inspired",
    description:
      "A timeless and sophisticated fragrance inspired by Armani with notes of bergamot, cedar, and vetiver.",
    price: 25.75,
    category: "Men's Fragrance",
    imageUrl: "/images/armani.jpeg",
    images: ["/images/armani.jpeg", "/images/armani.jpeg", "/images/armani.jpeg"],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "valentino",
    name: "Valentino Inspired",
    description:
      "A modern and charismatic fragrance inspired by Valentino with notes of bergamot, coffee, and leather.",
    price: 25.75,
    category: "Men's Fragrance",
    imageUrl: "/images/valentino.jpeg",
    images: ["/images/valentino.jpeg", "/images/valentino.jpeg", "/images/valentino.jpeg"],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "versace-eros",
    name: "Versace Eros Inspired",
    description: "A bold and sensual fragrance inspired by Versace Eros with notes of mint, green apple, and vanilla.",
    price: 25.75,
    category: "Men's Fragrance",
    imageUrl: "/images/versace-eros.jpeg",
    images: ["/images/versace-eros.jpeg", "/images/versace-eros.jpeg", "/images/versace-eros.jpeg"],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "ferragamo",
    name: "Ferragamo Inspired",
    description:
      "An elegant and refined fragrance inspired by Ferragamo with notes of bergamot, leather, and sandalwood.",
    price: 25.75,
    category: "Men's Fragrance",
    imageUrl: "/images/ferragamo.jpeg",
    images: ["/images/ferragamo.jpeg", "/images/ferragamo.jpeg", "/images/ferragamo.jpeg"],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "dior-sauvage",
    name: "Dior Sauvage Inspired",
    description:
      "A powerful and fresh fragrance inspired by Dior Sauvage with notes of bergamot, pepper, and ambroxan.",
    price: 25.75,
    category: "Men's Fragrance",
    imageUrl: "/images/dior-sauvage.jpeg",
    images: ["/images/dior-sauvage.jpeg", "/images/dior-sauvage.jpeg", "/images/dior-sauvage.jpeg"],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "invictus",
    name: "Invictus Inspired",
    description:
      "A victorious and masculine fragrance inspired by Invictus with notes of grapefruit, bay leaf, and guaiac wood.",
    price: 25.75,
    category: "Men's Fragrance",
    imageUrl: "/images/invictus.jpeg",
    images: ["/images/invictus.jpeg", "/images/invictus.jpeg", "/images/invictus.jpeg"],
    gender: "male",
    type: "fragrance",
  },
  {
    id: "jimmy-choo-men",
    name: "Jimmy Choo Men Inspired",
    description:
      "A sophisticated and modern fragrance inspired by Jimmy Choo Men with notes of lavender, pineapple leaf, and suede.",
    price: 25.75,
    category: "Men's Fragrance",
    imageUrl: "/images/jimmy-choo-men.jpeg",
    images: ["/images/jimmy-choo-men.jpeg", "/images/jimmy-choo-men.jpeg", "/images/jimmy-choo-men.jpeg"],
    gender: "male",
    type: "fragrance",
  },

  // Additional women's fragrances
  {
    id: "louis-vutton-lovers",
    name: "Louis Vuitton Lovers",
    description: "A romantic and sophisticated fragrance inspired by Louis Vuitton with floral and vanilla notes.",
    price: 25.75,
    category: "Women's Fragrance",
    imageUrl: "/images/louis-vutton-lovers.jpeg",
    images: [
      "/images/louis-vutton-lovers.jpeg",
      "/images/louis-vutton-lovers.jpeg",
      "/images/louis-vutton-lovers.jpeg",
    ],
    gender: "female",
    type: "fragrance",
  },
  {
    id: "miss-dior",
    name: "Miss Dior Inspired",
    description: "An elegant and feminine fragrance inspired by Miss Dior with notes of rose and jasmine.",
    price: 25.75,
    category: "Women's Fragrance",
    imageUrl: "/images/miss-dior.jpeg",
    images: ["/images/miss-dior.jpeg", "/images/miss-dior.jpeg", "/images/miss-dior.jpeg"],
    gender: "female",
    type: "fragrance",
  },
  {
    id: "miss-daisy",
    name: "Miss Daisy Inspired",
    description: "A fresh and youthful fragrance inspired by Marc Jacobs Daisy with floral and fruity notes.",
    price: 25.75,
    category: "Women's Fragrance",
    imageUrl: "/images/miss-daisy.jpeg",
    images: ["/images/miss-daisy.jpeg", "/images/miss-daisy.jpeg", "/images/miss-daisy.jpeg"],
    gender: "female",
    type: "fragrance",
  },
  {
    id: "crush-on-you",
    name: "Crush On You",
    description: "A playful and romantic fragrance with sweet and fruity notes that captivate the senses.",
    price: 25.75,
    category: "Women's Fragrance",
    imageUrl: "/images/crush-on-you.jpeg",
    images: ["/images/crush-on-you.jpeg", "/images/crush-on-you.jpeg", "/images/crush-on-you.jpeg"],
    gender: "female",
    type: "fragrance",
  },
  {
    id: "blush",
    name: "Blush",
    description: "A delicate and feminine fragrance with soft floral notes and a hint of sweetness.",
    price: 25.75,
    category: "Women's Fragrance",
    imageUrl: "/images/blush.jpeg",
    images: ["/images/blush.jpeg", "/images/blush.jpeg", "/images/blush.jpeg"],
    gender: "female",
    type: "fragrance",
  },
  {
    id: "i-want-chu",
    name: "I Want Chu",
    description: "A seductive and alluring fragrance with warm vanilla and amber notes.",
    price: 25.75,
    category: "Women's Fragrance",
    imageUrl: "/images/i-want-chu.jpeg",
    images: ["/images/i-want-chu.jpeg", "/images/i-want-chu.jpeg", "/images/i-want-chu.jpeg"],
    gender: "female",
    type: "fragrance",
  },
  {
    id: "baccarat-rouge-540",
    name: "Baccarat Rouge 540 Inspired",
    description: "A luxurious and complex fragrance inspired by Baccarat Rouge 540 with amber and woody notes.",
    price: 25.75,
    category: "Women's Fragrance",
    imageUrl: "/images/baccarat-rouge-540.jpeg",
    images: ["/images/baccarat-rouge-540.jpeg", "/images/baccarat-rouge-540.jpeg", "/images/baccarat-rouge-540.jpeg"],
    gender: "female",
    type: "fragrance",
  },
  {
    id: "louis-vutton-reeves",
    name: "Louis Vuitton Reeves Inspired",
    description: "A sophisticated and elegant fragrance inspired by Louis Vuitton with floral and woody notes.",
    price: 25.75,
    category: "Women's Fragrance",
    imageUrl: "/images/louis-vutton-reeves.jpeg",
    images: [
      "/images/louis-vutton-reeves.jpeg",
      "/images/louis-vutton-reeves.jpeg",
      "/images/louis-vutton-reeves.jpeg",
    ],
    gender: "female",
    type: "fragrance",
  },
  {
    id: "rihanna-crush",
    name: "Rihanna Crush Inspired",
    description: "A bold and confident fragrance inspired by Rihanna with fruity and floral notes.",
    price: 25.75,
    category: "Women's Fragrance",
    imageUrl: "/images/rihanna-crush.jpeg",
    images: ["/images/rihanna-crush.jpeg", "/images/rihanna-crush.jpeg", "/images/rihanna-crush.jpeg"],
    gender: "female",
    type: "fragrance",
  },
  {
    id: "pink-sugar-crush-on-you",
    name: "Pink Sugar Crush On You",
    description: "A sweet and playful fragrance with cotton candy and vanilla notes.",
    price: 25.75,
    category: "Women's Fragrance",
    imageUrl: "/images/pink-sugar-crush-on-you.jpeg",
    images: [
      "/images/pink-sugar-crush-on-you.jpeg",
      "/images/pink-sugar-crush-on-you.jpeg",
      "/images/pink-sugar-crush-on-you.jpeg",
    ],
    gender: "female",
    type: "fragrance",
  },
  {
    id: "beyonce-heat-ysl-myself",
    name: "Beyonce Heat YSL Myself Inspired",
    description: "A warm and sensual fragrance inspired by Beyonce Heat and YSL with spicy and floral notes.",
    price: 25.75,
    category: "Women's Fragrance",
    imageUrl: "/images/beyonce-heat.jpeg",
    images: ["/images/beyonce-heat.jpeg", "/images/beyonce-heat.jpeg", "/images/beyonce-heat.jpeg"],
    gender: "female",
    type: "fragrance",
  },
  {
    id: "louis-vurtton-california",
    name: "Louis Vuitton California Inspired",
    description: "A fresh and vibrant fragrance inspired by Louis Vuitton with citrus and floral notes.",
    price: 25.75,
    category: "Women's Fragrance",
    imageUrl: "/images/louis-vutton-california.jpeg",
    images: [
      "/images/louis-vutton-california.jpeg",
      "/images/louis-vutton-california.jpeg",
      "/images/louis-vutton-california.jpeg",
    ],
    gender: "female",
    type: "fragrance",
  },

  // Air fresheners
  {
    id: "wow-air-freshener",
    name: "Wow Air Freshener",
    description: "A captivating air freshener with a unique blend of exotic scents that will wow your senses.",
    price: 10,
    category: "Air Freshener",
    imageUrl: "/images/wow-air-freshener.jpeg",
    images: ["/images/wow-air-freshener.jpeg", "/images/wow-air-freshener.jpeg", "/images/wow-air-freshener.jpeg"],
    type: "air-freshener",
  },
  {
    id: "kool-air-freshener",
    name: "Kool Air Freshener",
    description: "A refreshing and cool air freshener with mint and ocean breeze notes for a crisp atmosphere.",
    price: 10,
    category: "Air Freshener",
    imageUrl: "/images/kool-air-freshener.jpeg",
    images: ["/images/kool-air-freshener.jpeg", "/images/kool-air-freshener.jpeg", "/images/kool-air-freshener.jpeg"],
    type: "air-freshener",
  },
  {
    id: "berry-air-freshener",
    name: "Berry Air Freshener",
    description: "A sweet and fruity air freshener with mixed berry notes that create a warm and inviting atmosphere.",
    price: 10,
    category: "Air Freshener",
    imageUrl: "/images/berry-air-freshener.jpeg",
    images: [
      "/images/berry-air-freshener.jpeg",
      "/images/berry-air-freshener.jpeg",
      "/images/berry-air-freshener.jpeg",
    ],
    type: "air-freshener",
  },
  {
    id: "hercules-air-freshener",
    name: "Hercules Air Freshener",
    description:
      "A strong and powerful air freshener with woody and spicy notes that last longer than standard fresheners.",
    price: 10,
    category: "Air Freshener",
    imageUrl: "/images/hercules-air-freshener.jpeg",
    images: [
      "/images/hercules-air-freshener.jpeg",
      "/images/hercules-air-freshener.jpeg",
      "/images/hercules-air-freshener.jpeg",
    ],
    type: "air-freshener",
  },
  {
    id: "chandelier-air-freshener",
    name: "Chandelier Car Air Freshener",
    description:
      "An elegant and luxurious hanging car air freshener with sophisticated notes of amber and vanilla for a premium car experience.",
    price: 10,
    category: "Car Air Freshener",
    imageUrl: "/images/chandelier-air-freshener.jpeg",
    images: [
      "/images/chandelier-air-freshener.jpeg",
      "/images/chandelier-air-freshener.jpeg",
      "/images/chandelier-air-freshener.jpeg",
    ],
    type: "air-freshener",
  },
  {
    id: "air-freshener-bundle",
    name: "Air Freshener 5-Pack Bundle",
    description:
      "Experience all our premium air fresheners with this bundle pack containing Wow, Kool, Berry, Hercules, and Chandelier air fresheners.",
    price: 35,
    category: "Air Freshener",
    imageUrl: "/images/air-freshener-bundle.jpeg",
    images: [
      "/images/air-freshener-bundle.jpeg",
      "/images/wow-air-freshener.jpeg",
      "/images/kool-air-freshener.jpeg",
      "/images/berry-air-freshener.jpeg",
      "/images/hercules-air-freshener.jpeg",
      "/images/chandelier-air-freshener.jpeg",
    ],
    type: "air-freshener",
  },

  // Child of God clothing
  {
    id: "child-of-god-white",
    name: "Child of God Hoodie - White",
    description: "A comfortable white hoodie featuring the Child of God design with Psalm 34:8 scripture on the back.",
    price: 60,
    category: "Clothing",
    imageUrl: "/images/child-of-god-white.jpeg",
    images: [
      "/images/child-of-god-white.jpeg",
      "/images/child-of-god-white.jpeg",
      "/images/child-of-god-white.jpeg",
      "/images/child-of-god-white.jpeg",
    ],
    gender: "unisex",
    type: "clothing",
  },
  {
    id: "child-of-god-grey",
    name: "Child of God Hoodie - Grey",
    description: "A comfortable grey hoodie featuring the Child of God design with Psalm 34:8 scripture on the back.",
    price: 60,
    category: "Clothing",
    imageUrl: "/images/child-of-god-grey.jpeg",
    images: ["/images/child-of-god-grey.jpeg", "/images/child-of-god-grey.jpeg", "/images/child-of-god-grey.jpeg"],
    gender: "unisex",
    type: "clothing",
  },
  {
    id: "child-of-god-black",
    name: "Child of God Hoodie - Black",
    description: "A comfortable black hoodie featuring the Child of God design with Psalm 34:8 scripture on the back.",
    price: 60,
    category: "Clothing",
    imageUrl: "/images/child-of-god-black.jpeg",
    images: ["/images/child-of-god-black.jpeg", "/images/child-of-god-black.jpeg", "/images/child-of-god-black.jpeg"],
    gender: "unisex",
    type: "clothing",
  },
]
