import type { Review } from "./types"

// Initial mock reviews data
export const initialReviews: Review[] = [
  {
    id: "review-1",
    productId: "louis-vuitton",
    name: "Michael T.",
    email: "michael@example.com",
    rating: 5,
    comment: "The Louis Vuitton inspired fragrance is amazing! Lasts all day and I get compliments everywhere I go.",
    date: "2023-12-15",
    verified: true,
  },
  {
    id: "review-2",
    productId: "louis-vuitton",
    name: "James K.",
    email: "james@example.com",
    rating: 4,
    comment: "Great scent that lasts for hours. Very similar to the designer version but at a fraction of the price.",
    date: "2023-11-20",
    verified: true,
  },
  {
    id: "review-3",
    productId: "sugar-girl",
    name: "Sarah L.",
    email: "sarah@example.com",
    rating: 5,
    comment: "Sugar Girl is my new favorite! The scent is perfect for everyday wear and the quality is exceptional.",
    date: "2023-12-05",
    verified: true,
  },
  {
    id: "review-4",
    productId: "creed-aventus",
    name: "David M.",
    email: "david@example.com",
    rating: 5,
    comment: "Incredible fragrance that smells just like the original Creed Aventus. Great longevity and projection.",
    date: "2023-10-18",
    verified: true,
  },
  {
    id: "review-5",
    productId: "baccarat-rouge-540",
    name: "Emily R.",
    email: "emily@example.com",
    rating: 5,
    comment: "This is an amazing dupe for Baccarat Rouge 540. I've had so many compliments wearing this!",
    date: "2023-11-30",
    verified: true,
  },
  {
    id: "review-6",
    productId: "wow-air-freshener",
    name: "Jessica T.",
    email: "jessica@example.com",
    rating: 4,
    comment: "Love the scent of this air freshener. It lasts a long time and makes my car smell amazing.",
    date: "2023-12-10",
    verified: true,
  },
  {
    id: "review-7",
    productId: "child-of-god-black",
    name: "Robert J.",
    email: "robert@example.com",
    rating: 5,
    comment: "The hoodie is super comfortable and the design is beautiful. I wear it all the time!",
    date: "2023-11-25",
    verified: true,
  },
]
